import { FEC_MIN_RATE } from "./constants.js";

export const state = {
  role: "share",
  client_id: crypto.randomUUID(),
  session_id: "",

  zt_started: false,
  libzt_node_online: false,
  libzt_network_ready: false,
  libzt_reonline_need_restore: false,
  libzt_offline_timer: null,
  libzt_offline_since: 0,
  libzt_transport_invalidated: false,
  libzt_route_status: "UNKNOWN",
  libzt_route_changed_at: 0,

  connecting: false,
  manual_disconnect: false,
  auto_reconnect_enabled: false,
  reconnect_timer: null,
  reconnect_attempts: 0,
  reconnect_epoch: 0,
  transport_resetting: false,

  signal_connected: false,
  signal_listening: false,
  last_signal_activity_at: 0,
  signal_pump_timer: null,
  signal_poll_busy: false,

  media_transport_open: false,
  media_peer_known: false,
  media_peer_unknown_notified: false,
  last_media_activity_at: 0,
  media_pump_timer: null,
  media_poll_busy: false,

  libzt_event_pump_timer: null,
  libzt_event_poll_busy: false,

  start_requested: false,
  peer_ready: false,
  peer_target_id: "",
  last_user_selected_profile_key: "",

  local_stream: null,
  capture_timer: null,
  capture_reader: null,
  capture_loop_token: 0,
  capture_mode: "",
  track_processor_failure_count: 0,
  encoder: null,
  decoder: null,
  decoder_generation: 0,
  active_video_codec_key: "h264",
  active_decoder_codec_key: "",
  encoder_configured: false,
  decoder_configured: false,
  force_next_keyframe: false,
  last_keyframe_at: 0,
  last_capture_at: 0,
  capture_busy: false,
  capture_motion_level: "high",
  capture_motion_score: 255,
  capture_motion_canvas: null,
  capture_motion_ctx: null,
  capture_motion_prev_luma: null,

  seq: 1,
  frame_id: 1,
  retrans_cache: new Map(),

  rx_frame_buffer: new Map(),
  rx_completed_frames: new Map(),
  rx_need_keyframe: true,
  rx_decoder_awaiting_output: false,
  rx_first_media_packet_at: 0,
  rx_last_complete_frame_at: 0,
  rx_last_frame_assembled_at: 0,
  rx_last_complete_frame_id: 0,
  rx_last_decode_input_at: 0,
  rx_last_decode_output_at: 0,
  rx_next_decode_frame_id: null,
  rx_decode_wait_frame_id: null,
  rx_decode_wait_started_at: 0,
  rx_decode_flush_busy: false,
  rx_pli_last_sent_at: 0,
  rx_start_at: 0,
  rx_play_clock_wall_ms: 0,
  rx_play_clock_media_ts_ms: 0,
  rx_expected_seq: null,
  rx_delta_recv_packets: 0,
  rx_delta_lost_packets: 0,
  rx_loss_burst_current: 0,
  rx_loss_burst_max: 0,
  rx_jitter_ms: 10,
  rx_prev_transit_ms: null,
  rx_target_delay_ms: 30,
  bad_link_mode: false,
  bad_link_until: 0,
  bad_link_last_trigger_at: 0,
  bad_link_last_reason: "",
  bad_link_trigger_streak: 0,
  bad_link_trigger_reason: "",
  bad_link_signal_state: "",
  bad_link_signal_timer: null,
  rx_consecutive_drop_frames: 0,
  rx_last_drop_at: 0,
  rx_reorder_pending: new Map(),
  rx_expired_frames: new Map(),

  cc_timer: null,
  last_cc_req_ts: 0,
  last_cc_req_wall_ms: 0,
  last_cc_probe_id: 0,
  awaiting_cc_probe: false,
  cc: {
    vbvTargetBps: 2_000_000,
    vbvBucketCapacityBits: 800_000,
    vbvTokensBits: 800_000,
    vbvDebtFloorBits: -280_000,
    vbvPendingBits: 0,
    vbvReservationQueue: [],
    vbvEncoderBitrateBps: 2_000_000,
    vbvMaxFrameBytes: 180_000,
    vbvLastRefillAt: 0,
    vbvMotionBudgetScale: 1,
    currentFps: 30,
    currentFecRate: FEC_MIN_RATE,
    activeProfileKey: "",
    activeEncoderConfigKey: "",
    activeEncoderBitrateBucketBps: 0,
    lastPolicyLogKey: "",
    fecLastAdjustAt: 0,
    minRttMs: Infinity,
    rttMs: 0,
    queueDelayMs: 0,
    lossPermille: 0,
    lastFpsSwitchAt: 0,
    lastPolicySwitchAt: 0,
    lastEncoderReconfigureAt: 0,
    rttSamples: [],
  },

  stats_timer: null,
  metrics_log_timer: null,
  tx_window_bytes: 0,
  tx_window_frames: 0,
  rx_window_bytes: 0,
  rx_window_frames: 0,

  rx_pkts_sec: 0,
  rx_bytes_sec: 0,
  rx_frames_completed_sec: 0,
  rx_frames_played_sec: 0,
  rx_drop_deadline_sec: 0,
  rx_late_after_deadline_pkts_sec: 0,
  rx_expired_frames_sec: 0,
  rx_missing_on_deadline_pkts_sec: 0,
  rx_completed_frame_pkt_total_sec: 0,
  rx_data_pkts_sec: 0,
  rx_out_of_order_pkts_sec: 0,
  rx_nack_enqueued_sec: 0,
  rx_nack_sent_sec: 0,
  rx_nack_active_frames_sec: 0,
  rx_nack_budget_active_frames: new Set(),
  rx_nack_skipped_rtt_sec: 0,
  rx_nack_skipped_missing_sec: 0,
  rx_nack_skipped_rounds_sec: 0,
  pli_sent_ts: [],

  tx_pkts_sec: 0,
  tx_bytes_sec: 0,
  tx_captured_frames_sec: 0,
  tx_capture_skip_cadence_sec: 0,
  tx_encode_attempt_sec: 0,
  tx_encode_budget_drop_sec: 0,
  tx_encoded_frames_sec: 0,
  tx_frames_sent_sec: 0,
  tx_keyframes_sec: 0,
  tx_frame_pkt_total_sec: 0,
  nack_rx_sec: 0,
  pli_rx_ts: [],
};

// 选择器简写，便于集中获取 DOM。
